### ISSUE TITLE
SendChat(), ShowDialog(), etc does not work

### ISSUE THREAD

**Issue by imthatgin** [Slider1338/GTA-API#4]
These are broken.

Can you tell me how you find the memory addresses? I am happy to make an update to the code.

**Comment by Slider1338** [comment]
@ryan-kingstone I'm really sure for my very very very delayed answer... But as you can see, this project will no longer be maintained use this one instead: https://github.com/SAMPProjects/Open-SAMP-API

And the forum: forum.samp-api.net
